image:
  file: .gitpod.Dockerfile

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3005
    onOpen: ignore
  - port: 3306
    onOpen: ignore
  - port: 8000
    onOpen: ignore
  - port: 8001
    onOpen: ignore
  - port: 8002
    onOpen: ignore
  - port: 9000
    onOpen: ignore
    visibility: private
  - port: 9009
    onOpen: ignore
    visibility: private

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - before: bash .gp/bash/before-tasks.sh
    init: |
      bash .gp/bash/init-gitpod.sh
      bash .gp/bash/init-optional-scaffolding.sh
      bash .gp/bash/init-project.sh
      bash .gp/bash/init-complete.sh
    name: Main Terminal
  - openMode: split-right
    command: |
      bash .gp/bash/start-server.sh
    name: Web Server
  - openMode: split-right
    command: |
      if bash .gp/bash/open-preview.sh; then exit; else bash .gp/bash/patch-preview.sh; fi
    name: Extra Terminal

vscode:
  extensions:
    - felixfbecker.php-debug